apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "hello-world-maven.fullname" . }}-netpol
  labels:
    {{- include "hello-world-maven.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "hello-world-maven.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    # Allow ingress from same namespace
    - namespaceSelector:
        matchLabels:
          name: {{ .Release.Namespace }}
    # Allow ingress from ingress controller namespace
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS to external services (for health checks, metrics, etc.)
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP for health checks and internal services
  - to: []
    ports:
    - protocol: TCP
      port: 80
  # Allow egress to Kubernetes API server
  - to: []
    ports:
    - protocol: TCP
      port: 6443