apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hello-world-maven.fullname" . }}-pdb
  labels:
    {{- include "hello-world-maven.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "hello-world-maven.selectorLabels" . | nindent 6 }}
---
{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "hello-world-maven.fullname" . }}-psp
  labels:
    {{- include "hello-world-maven.labels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hello-world-maven.fullname" . }}-psp-role
  labels:
    {{- include "hello-world-maven.labels" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - {{ include "hello-world-maven.fullname" . }}-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hello-world-maven.fullname" . }}-psp-binding
  labels:
    {{- include "hello-world-maven.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ include "hello-world-maven.fullname" . }}-psp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "hello-world-maven.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}